# Generated by Django 3.2.5 on 2023-09-01 15:07

import datetime
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='auth.user')),
                ('uuid', models.UUIDField(default=uuid.UUID('9b0c5fab-def0-43e4-8a0d-3142f271fa48'), editable=False, primary_key=True, serialize=False, unique=True)),
                ('age', models.IntegerField(null=True)),
                ('can_be_contacted', models.BooleanField(default=False)),
                ('can_data_be_shared', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2023, 9, 1, 17, 7, 49, 574888), editable=False)),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2023, 9, 1, 17, 7, 49, 574888))),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('uuid', models.UUIDField(default=uuid.UUID('f90787b2-4330-4440-a032-754167f06af2'), editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField()),
                ('project_type', models.CharField(choices=[('BACKEND', 'Backend'), ('FRONTEND', 'Frontend'), ('IOS', 'iOS'), ('ANDROID', 'Android')], default='BACKEND', max_length=128)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project.customuser')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('uuid', models.UUIDField(default=uuid.UUID('f90787b2-4330-4440-a032-754167f06af2'), editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2023, 9, 1, 17, 7, 49, 575888), editable=False)),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2023, 9, 1, 17, 7, 49, 575888))),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='LOW', max_length=128)),
                ('tag', models.CharField(choices=[('BUG', 'Bug'), ('FEATURE', 'Feature'), ('TASK', 'Task')], default='FEATURE', max_length=128)),
                ('status', models.CharField(choices=[('TODO', 'To Do'), ('INPROGRESS', 'In Progress'), ('FINISHED', 'Finished')], default='TODO', max_length=128)),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignee', to='project.customuser')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project.customuser')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='project.project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('uuid', models.UUIDField(default=uuid.UUID('f90787b2-4330-4440-a032-754167f06af2'), editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2023, 9, 1, 17, 7, 49, 575888), editable=False)),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2023, 9, 1, 17, 7, 49, 575888))),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project.customuser')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributors', to='project.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='project.customuser')),
            ],
            options={
                'unique_together': {('user', 'project')},
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('uuid', models.UUIDField(default=uuid.UUID('f90787b2-4330-4440-a032-754167f06af2'), editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2023, 9, 1, 17, 7, 49, 575888), editable=False)),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2023, 9, 1, 17, 7, 49, 575888))),
                ('content', models.TextField()),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project.customuser')),
                ('contributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.contributor')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.issue')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
