# Generated by Django 3.2.5 on 2023-08-21 19:34

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 21, 21, 34, 5, 370956), editable=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 21, 21, 34, 5, 371957)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('48d0cdb3-cbd3-42ed-a96a-6169d9aae555'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='contributor',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 21, 21, 34, 5, 370956), editable=False),
        ),
        migrations.AlterField(
            model_name='contributor',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 21, 21, 34, 5, 371957)),
        ),
        migrations.AlterField(
            model_name='contributor',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('48d0cdb3-cbd3-42ed-a96a-6169d9aae555'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 21, 21, 34, 5, 370956), editable=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 21, 21, 34, 5, 371957)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('48d0cdb3-cbd3-42ed-a96a-6169d9aae555'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 21, 21, 34, 5, 370956), editable=False),
        ),
        migrations.AlterField(
            model_name='issue',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 21, 21, 34, 5, 371957)),
        ),
        migrations.AlterField(
            model_name='issue',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('48d0cdb3-cbd3-42ed-a96a-6169d9aae555'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('48d0cdb3-cbd3-42ed-a96a-6169d9aae555'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
