# Generated by Django 3.2.5 on 2023-09-14 10:49

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20230902_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 14, 12, 49, 26, 686347), editable=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 14, 12, 49, 26, 686347)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('dbc1b309-e10c-43ad-b025-9d1a5a7a630b'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='contributor',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 14, 12, 49, 26, 686347), editable=False),
        ),
        migrations.AlterField(
            model_name='contributor',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 14, 12, 49, 26, 686347)),
        ),
        migrations.AlterField(
            model_name='contributor',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('dbc1b309-e10c-43ad-b025-9d1a5a7a630b'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 14, 12, 49, 26, 686347), editable=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 14, 12, 49, 26, 686347)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('7947cc99-fe02-4685-939f-f105dbff04b2'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 14, 12, 49, 26, 686347), editable=False),
        ),
        migrations.AlterField(
            model_name='issue',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 14, 12, 49, 26, 686347)),
        ),
        migrations.AlterField(
            model_name='issue',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('dbc1b309-e10c-43ad-b025-9d1a5a7a630b'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('dbc1b309-e10c-43ad-b025-9d1a5a7a630b'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
