# Generated by Django 3.2.5 on 2023-09-14 10:53

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20230914_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 14, 12, 53, 50, 18472), editable=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='project.issue'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 14, 12, 53, 50, 18472)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('95ebd591-b710-4014-b71a-8d6abc127473'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='contributor',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 14, 12, 53, 50, 18472), editable=False),
        ),
        migrations.AlterField(
            model_name='contributor',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 14, 12, 53, 50, 18472)),
        ),
        migrations.AlterField(
            model_name='contributor',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('95ebd591-b710-4014-b71a-8d6abc127473'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 14, 12, 53, 50, 18472), editable=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 14, 12, 53, 50, 18472)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('fc7a5df0-5afd-41fa-9aa2-7e34dada848e'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 14, 12, 53, 50, 18472), editable=False),
        ),
        migrations.AlterField(
            model_name='issue',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 14, 12, 53, 50, 18472)),
        ),
        migrations.AlterField(
            model_name='issue',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('95ebd591-b710-4014-b71a-8d6abc127473'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('95ebd591-b710-4014-b71a-8d6abc127473'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
